import {
  color,
  space,
  fontFamily,
  fontSize,
  fontWeight,
  lineHeight,
  letterSpacing,
  radius,
  border,
  shadow,
  duration,
  easing,
  breakpoint,
  zIndex,
} from '../primitive/index.js';

export const semanticLight = {
  color: {
    bg: color.ink[1000],
    'bg-subtle': color.ink[900],
    'bg-muted': color.ink[800],
    'bg-inverse': color.ink[0],
    fg: color.ink[0],
    'fg-muted': color.ink[400],
    'fg-subtle': color.ink[300],
    'fg-inverse': color.ink[1000],
    accent: color.cobalt[500],
    'accent-hover': color.cobalt[600],
    'accent-active': color.cobalt[700],
    'accent-fg': color.ink[1000],
    'accent-subtle': color.cobalt[100],
    border: color.alpha.inkHairline,
    'border-strong': color.ink[200],
    'border-subtle': color.alpha.inkSubtle,
    focus: color.alpha.focusRing,
    success: color.success[500],
    'success-subtle': color.success[100],
    warning: color.warning[500],
    'warning-subtle': color.warning[100],
    danger: color.danger[500],
    'danger-subtle': color.danger[100],
    'chart-1': '#4A72CC',
    'chart-2': '#1F7A7A',
    'chart-3': '#D97706',
    'chart-4': '#B83280',
    'chart-5': '#2B8A3E',
    'chart-6': '#7B3FE4',
  },
  space,
  font: {
    display: fontFamily.display,
    body: fontFamily.body,
    mono: fontFamily.mono,
  },
  'font-size': fontSize,
  'font-weight': fontWeight,
  'line-height': lineHeight,
  'letter-spacing': letterSpacing,
  radius,
  border,
  shadow,
  duration,
  easing,
  breakpoint,
  'z-index': zIndex,
} as const;

export type SemanticTokens = typeof semanticLight;
